// Mock data for Bunyan - used when Supabase is not configured

export const mockUser = {
  id: "user-001",
  email: "mohamed@bunyan.ai",
  full_name: "Mohamed El-Sayed",
  company_name: "El-Sayed Construction",
  role: "contractor",
  avatar_url: null,
  phone: "+20 100 123 4567",
};

export const mockProjects = [
  {
    id: "proj-001",
    name: "Cairo Business District - Tower B",
    description: "Mixed-use commercial tower, 45 floors with sustainable design certification",
    location: "Cairo, Egypt",
    status: "active",
    budget: 12500000,
    spent: 8750000,
    waste_percentage: 4.2,
    sustainability_score: 87,
    co2_saved: 1240,
    start_date: "2025-03-15",
    end_date: "2026-09-30",
    created_at: "2025-03-10T08:00:00Z",
  },
  {
    id: "proj-002",
    name: "New Administrative Capital Residential Complex Phase 2",
    description: "Eco-friendly residential buildings with zero-waste target",
    location: "New Administrative Capital, Egypt",
    status: "active",
    budget: 8200000,
    spent: 3280000,
    waste_percentage: 2.8,
    sustainability_score: 94,
    co2_saved: 890,
    start_date: "2025-06-01",
    end_date: "2026-12-15",
    created_at: "2025-05-20T08:00:00Z",
  },
  {
    id: "proj-003",
    name: "Alexandria Waterfront Promenade",
    description: "Public walkway with sustainable infrastructure",
    location: "Alexandria, Egypt",
    status: "planning",
    budget: 3500000,
    spent: 175000,
    waste_percentage: 0,
    sustainability_score: 0,
    co2_saved: 0,
    start_date: "2026-01-15",
    end_date: "2026-08-30",
    created_at: "2025-11-05T08:00:00Z",
  },
  {
    id: "proj-004",
    name: "Cairo Metro Station - Green Line",
    description: "Underground transit station with energy-efficient systems",
    location: "Cairo, Egypt",
    status: "completed",
    budget: 5800000,
    spent: 5510000,
    waste_percentage: 3.1,
    sustainability_score: 91,
    co2_saved: 2100,
    start_date: "2024-06-01",
    end_date: "2025-11-30",
    created_at: "2024-05-15T08:00:00Z",
  },
];

export const mockMaterials = [
  {
    id: "mat-001",
    name: "EcoSteel Rebar Grade 60",
    category: "Steel",
    description: "High-strength recycled steel rebar with 85% recycled content",
    price: 3200,
    unit: "ton",
    supplier_name: "GreenSteel Arabia",
    eco_score: 92,
    co2_footprint: 1.2,
    recycled_content: 85,
    certification: "LEED Certified",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-002",
    name: "SustainCrete C40 Ready Mix",
    category: "Concrete",
    description: "Low-carbon concrete mix with 40% slag cement replacement",
    price: 450,
    unit: "m³",
    supplier_name: "Arabian Cement Co.",
    eco_score: 88,
    co2_footprint: 0.8,
    recycled_content: 40,
    certification: "ISO 14001",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-003",
    name: "BioInsulate Pro R-30",
    category: "Insulation",
    description: "Plant-based thermal insulation panels, zero VOC",
    price: 185,
    unit: "m²",
    supplier_name: "Desert Green Materials",
    eco_score: 96,
    co2_footprint: 0.3,
    recycled_content: 70,
    certification: "Cradle to Cradle",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-004",
    name: "SolarGlass Facade Panel",
    category: "Glass",
    description: "Triple-glazed photovoltaic glass panel for building facades",
    price: 890,
    unit: "m²",
    supplier_name: "Vision Glass KSA",
    eco_score: 91,
    co2_footprint: 0.6,
    recycled_content: 30,
    certification: "BREEAM Excellent",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-005",
    name: "RecycleBlock AAC B4",
    category: "Blocks",
    description: "Autoclaved aerated concrete blocks from recycled materials",
    price: 28,
    unit: "piece",
    supplier_name: "Egyptian Block Co.",
    eco_score: 85,
    co2_footprint: 0.4,
    recycled_content: 60,
    certification: "EGBC Certified",
    in_stock: true,
    verified: true,
    image_url: null,
  },
];

// Recycled & Upcycled Products Marketplace
export const mockRecycledProducts = [
  {
    id: "rp-001",
    name: "Industrial Concrete Pendant Lamp",
    category: "Lighting",
    description: "Modern pendant lamp handcrafted from recycled construction concrete. Features authentic industrial texture with embedded aggregates. Complete with eco-friendly LED bulb and adjustable cord.",
    price: 850,
    unit: "piece",
    creator_name: "Cairo Upcycle Studio",
    eco_score: 98,
    recycled_content: 95,
    certification: "100% Recycled Materials",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/im8p7f.jpeg",
    materials_source: "Demolished building concrete from New Administrative Capital projects",
    dimensions: "Diameter: 25cm, Height: 20cm",
    weight: "3.5 kg",
    handmade: true,
    customizable: true,
    features: ["Unique texture", "LED compatible", "Adjustable height", "Easy installation"],
    tags: ["Lighting", "Industrial", "Minimalist", "Eco-Friendly"],
  },
  {
    id: "rp-002",
    name: "Abstract Geometric Wall Art - Concrete Canvas",
    category: "Wall Art",
    description: "One-of-a-kind abstract wall art combining recycled concrete pieces with vibrant eco-paint accents. Each piece tells a story of urban renewal and sustainable creativity.",
    price: 1200,
    unit: "piece",
    creator_name: "Nile Green Artists Collective",
    eco_score: 97,
    recycled_content: 92,
    certification: "Sustainable Materials Certified",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/ybebf3.jpeg",
    materials_source: "Concrete waste from Alexandria waterfront renovation",
    dimensions: "60cm x 60cm x 4cm",
    weight: "8 kg",
    handmade: true,
    customizable: true,
    features: ["Unique artwork", "Ready to hang", "Signed by artist", "Weatherproof finish"],
    tags: ["Art", "Wall Decor", "Modern", "Statement Piece"],
  },
  {
    id: "rp-003",
    name: "Minimalist Concrete Planter with Greenery",
    category: "Home Decor",
    description: "Elegant geometric planter crafted from upcycled concrete with natural gray finish. Perfect for succulents, cacti, or small indoor plants. Includes drainage system.",
    price: 420,
    unit: "piece",
    creator_name: "GreenCraft Egypt",
    eco_score: 96,
    recycled_content: 98,
    certification: "Zero Waste Production",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/ybebf3.jpeg",
    materials_source: "Leftover concrete from residential construction sites in Giza",
    dimensions: "20cm x 20cm x 25cm",
    weight: "4.2 kg",
    handmade: true,
    customizable: false,
    features: ["Drainage holes", "Sealed interior", "Non-toxic finish", "Indoor/outdoor"],
    tags: ["Planter", "Home Decor", "Plants", "Minimalist"],
  },
  {
    id: "rp-004",
    name: "Industrial Wall Clock - Concrete Circle",
    category: "Home Decor",
    description: "Statement wall clock with raw concrete face and eco-painted hour markers. Silent quartz movement. Perfect blend of industrial design and functional art.",
    price: 680,
    unit: "piece",
    creator_name: "Delta Design Workshop",
    eco_score: 94,
    recycled_content: 90,
    certification: "Handmade in Egypt",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/ir0p9o.jpeg",
    materials_source: "Recycled concrete from office building demolition",
    dimensions: "Diameter: 40cm, Depth: 3cm",
    weight: "3.8 kg",
    handmade: true,
    customizable: false,
    features: ["Silent mechanism", "Battery included", "Wall mounting kit", "Unique texture"],
    tags: ["Clock", "Wall Decor", "Industrial", "Functional Art"],
  },
  {
    id: "rp-005",
    name: "Geometric Bookends Set - Concrete Sculptures",
    category: "Office Decor",
    description: "Pair of modern geometric bookends handcrafted from recycled concrete. Heavy-duty design keeps books upright while adding architectural interest to any shelf.",
    price: 550,
    unit: "pair",
    creator_name: "Cairo Upcycle Studio",
    eco_score: 95,
    recycled_content: 94,
    certification: "100% Recycled Materials",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/ybebf3.jpeg",
    materials_source: "Construction waste from Smart Village projects",
    dimensions: "Each: 12cm x 15cm x 18cm",
    weight: "2.8 kg per piece",
    handmade: true,
    customizable: false,
    features: ["Non-slip base", "Heavy weight", "Modern design", "Set of 2"],
    tags: ["Bookends", "Office", "Organization", "Sculpture"],
  },
  {
    id: "rp-006",
    name: "Concrete Candle Holder Trio",
    category: "Home Decor",
    description: "Set of three varying-height candle holders crafted from upcycled concrete. Creates stunning ambiance with natural material texture. Fits standard taper candles.",
    price: 480,
    unit: "set",
    creator_name: "Nile Green Artists Collective",
    eco_score: 97,
    recycled_content: 96,
    certification: "Eco-Certified Handmade",
    in_stock: true,
    verified: true,
    image_url: "https://files.catbox.moe/ch2f54.jpeg",
    materials_source: "Recycled concrete from hospital construction project in Mansoura",
    dimensions: "Heights: 15cm, 20cm, 25cm",
    weight: "1.5 kg total",
    handmade: true,
    customizable: false,
    features: ["Set of 3", "Stable base", "Natural finish", "Candles not included"],
    tags: ["Candle Holder", "Home Decor", "Ambient Lighting", "Gift Set"],
  },
  {
    id: "rp-007",
    name: "Colorful Mosaic Wall Art from Broken Tiles",
    category: "Wall Art",
    description: "Vibrant mosaic artwork created from broken ceramic tiles salvaged from construction sites. Each piece is unique with intricate geometric patterns in multiple colors.",
    price: 1450,
    unit: "piece",
    creator_name: "Mosaic Masters Cairo",
    eco_score: 99,
    recycled_content: 100,
    certification: "100% Salvaged Materials",
    in_stock: true,
    verified: true,
    image_url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80",
    materials_source: "Broken tiles from bathroom renovations across Cairo",
    dimensions: "70cm x 70cm x 2cm",
    weight: "7.5 kg",
    handmade: true,
    customizable: true,
    features: ["Grouted finish", "Sealed surface", "Mounting hardware", "UV resistant"],
    tags: ["Mosaic", "Wall Art", "Colorful", "Mediterranean Style"],
  },
  {
    id: "rp-008",
    name: "Concrete Jewelry Organizer Stand",
    category: "Organization",
    description: "Elegant jewelry organizer with ring cone, earring hooks, and small trays. Handcrafted from recycled concrete with smooth polished finish. Perfect for dresser or vanity.",
    price: 520,
    unit: "piece",
    creator_name: "GreenCraft Egypt",
    eco_score: 96,
    recycled_content: 93,
    certification: "Handcrafted Sustainable",
    in_stock: true,
    verified: true,
    image_url: "https://images.unsplash.com/photo-1611652022419-a9419f74343a?w=800&q=80",
    materials_source: "Concrete leftovers from commercial tower projects",
    dimensions: "30cm x 15cm x 12cm",
    weight: "2.6 kg",
    handmade: true,
    customizable: false,
    features: ["Multiple compartments", "Polished finish", "Anti-scratch base", "Multi-functional"],
    tags: ["Jewelry", "Organization", "Storage", "Vanity Decor"],
  },
  {
    id: "rp-009",
    name: "Modern Concrete Vase with Geometric Pattern",
    category: "Home Decor",
    description: "Tall cylindrical vase with subtle geometric band detailing. Made from upcycled concrete with waterproof interior coating. Perfect for fresh or dried flowers.",
    price: 580,
    unit: "piece",
    creator_name: "Delta Design Workshop",
    eco_score: 95,
    recycled_content: 91,
    certification: "Eco-Friendly Production",
    in_stock: true,
    verified: true,
    image_url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80",
    materials_source: "Damaged concrete from infrastructure projects",
    dimensions: "Height: 35cm, Diameter: 12cm",
    weight: "3.2 kg",
    handmade: true,
    customizable: false,
    features: ["Waterproof interior", "Stable base", "Natural texture", "Versatile style"],
    tags: ["Vase", "Home Decor", "Flowers", "Centerpiece"],
  },
  {
    id: "rp-010",
    name: "Rustic Concrete Desk Organizer",
    category: "Office Decor",
    description: "Multi-compartment desk organizer with slots for pens, phone, business cards, and small supplies. Raw concrete finish with modern industrial aesthetic.",
    price: 390,
    unit: "piece",
    creator_name: "Cairo Upcycle Studio",
    eco_score: 94,
    recycled_content: 89,
    certification: "Recycled Materials",
    in_stock: true,
    verified: false,
    image_url: "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=800&q=80",
    materials_source: "Mixed concrete waste from various Cairo projects",
    dimensions: "25cm x 15cm x 8cm",
    weight: "2.1 kg",
    handmade: true,
    customizable: false,
    features: ["5 compartments", "Phone slot", "Non-slip bottom", "Compact design"],
    tags: ["Desk Organizer", "Office", "Storage", "Productivity"],
  },
  {
    id: "rp-011",
    name: "Concrete Coaster Set with Cork Base",
    category: "Home Decor",
    description: "Set of 6 hand-poured concrete coasters with cork backing to protect surfaces. Each with unique texture pattern. Comes in wooden storage box.",
    price: 280,
    unit: "set",
    creator_name: "GreenCraft Egypt",
    eco_score: 93,
    recycled_content: 88,
    certification: "Sustainable Craft",
    in_stock: true,
    verified: true,
    image_url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=800&q=80",
    materials_source: "Small concrete leftovers from construction sites",
    dimensions: "Each: 10cm diameter x 1cm thick",
    weight: "1.2 kg total",
    handmade: true,
    customizable: false,
    features: ["Cork backed", "Set of 6", "Storage box", "Heat resistant"],
    tags: ["Coasters", "Tableware", "Home Decor", "Gift Set"],
  },
  {
    id: "rp-012",
    name: "Large Industrial Concrete Mirror Frame",
    category: "Wall Decor",
    description: "Bold statement mirror with thick recycled concrete frame. Raw industrial finish with smooth mirror glass. Perfect for entryway, bedroom, or bathroom.",
    price: 1650,
    unit: "piece",
    creator_name: "Delta Design Workshop",
    eco_score: 92,
    recycled_content: 87,
    certification: "Handcrafted",
    in_stock: true,
    verified: true,
    image_url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    materials_source: "Salvaged concrete from building renovations",
    dimensions: "80cm x 60cm (mirror: 50cm x 40cm)",
    weight: "12 kg",
    handmade: true,
    customizable: true,
    features: ["Premium mirror glass", "Wall mount kit", "Heavy duty", "Unique finish"],
    tags: ["Mirror", "Wall Decor", "Statement Piece", "Industrial Decor"],
  },
];

// Additional construction materials (not actively used in marketplace)
export const mockConstructionMaterials = [
  {
    id: "mat-006",
    name: "EcoTimber CLT Panel",
    category: "Wood",
    description: "Cross-laminated timber from certified sustainable forests",
    price: 620,
    unit: "m³",
    supplier_name: "Timber Gulf LLC",
    eco_score: 94,
    co2_footprint: -0.5,
    recycled_content: 0,
    certification: "FSC Certified",
    in_stock: false,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-007",
    name: "GreenPipe PVC-Free",
    category: "Piping",
    description: "Bio-based plumbing pipes with zero PVC content",
    price: 42,
    unit: "meter",
    supplier_name: "AquaFlow Systems",
    eco_score: 89,
    co2_footprint: 0.2,
    recycled_content: 45,
    certification: "NSF Certified",
    in_stock: true,
    verified: false,
    image_url: null,
  },
  {
    id: "mat-008",
    name: "CoolRoof Reflective Membrane",
    category: "Roofing",
    description: "High-SRI reflective roofing membrane, reduces cooling costs by 30%",
    price: 95,
    unit: "m²",
    supplier_name: "SkyShield Roofing",
    eco_score: 87,
    co2_footprint: 0.5,
    recycled_content: 25,
    certification: "Energy Star",
    in_stock: true,
    verified: true,
    image_url: null,
  },
];

export const mockBills = [
  {
    id: "bill-001",
    project_id: "proj-001",
    title: "Steel Rebar Delivery - Batch 12",
    amount: 384000,
    category: "Materials",
    vendor: "GreenSteel Arabia",
    status: "paid",
    created_at: "2025-12-10T08:00:00Z",
  },
  {
    id: "bill-002",
    project_id: "proj-001",
    title: "Concrete Pour - Level 28-30",
    amount: 225000,
    category: "Materials",
    vendor: "Arabian Cement Co.",
    status: "approved",
    created_at: "2025-12-15T08:00:00Z",
  },
  {
    id: "bill-003",
    project_id: "proj-002",
    title: "Insulation Installation Phase 3",
    amount: 156000,
    category: "Labor & Materials",
    vendor: "Desert Green Materials",
    status: "pending",
    created_at: "2026-01-05T08:00:00Z",
  },
];

export const mockActivityLogs = [
  {
    id: "log-001",
    action: "project_updated",
    description: "Updated waste percentage for King Abdullah Tower B",
    created_at: "2026-02-15T08:30:00Z",
  },
  {
    id: "log-002",
    action: "bill_scanned",
    description: "Scanned and processed invoice from GreenSteel Arabia",
    created_at: "2026-02-14T16:45:00Z",
  },
  {
    id: "log-003",
    action: "ai_analysis",
    description: "AI generated cost optimization report for New Capital Phase 2",
    created_at: "2026-02-14T11:20:00Z",
  },
  {
    id: "log-004",
    action: "material_added",
    description: "Added SolarGlass Facade Panels to comparison list",
    created_at: "2026-02-13T09:15:00Z",
  },
  {
    id: "log-005",
    action: "project_created",
    description: "Created new project: Alexandria Waterfront Promenade",
    created_at: "2026-02-12T14:00:00Z",
  },
];

export const mockAnalyticsData = {
  wasteReduction: [
    { month: "Sep", value: 12.5 },
    { month: "Oct", value: 10.8 },
    { month: "Nov", value: 8.9 },
    { month: "Dec", value: 7.2 },
    { month: "Jan", value: 5.6 },
    { month: "Feb", value: 4.2 },
  ],
  co2Reduction: [
    { month: "Sep", value: 180 },
    { month: "Oct", value: 320 },
    { month: "Nov", value: 540 },
    { month: "Dec", value: 780 },
    { month: "Jan", value: 1050 },
    { month: "Feb", value: 1240 },
  ],
  budgetDistribution: [
    { name: "Materials", value: 45, color: "#102a4e" },
    { name: "Labor", value: 25, color: "#2e8c58" },
    { name: "Equipment", value: 15, color: "#788593" },
    { name: "Permits", value: 8, color: "#3aa86a" },
    { name: "Other", value: 7, color: "#9aa4ae" },
  ],
  monthlyOptimization: [
    { month: "Sep", saved: 45000, target: 60000 },
    { month: "Oct", saved: 62000, target: 60000 },
    { month: "Nov", saved: 78000, target: 75000 },
    { month: "Dec", saved: 91000, target: 80000 },
    { month: "Jan", saved: 105000, target: 90000 },
    { month: "Feb", saved: 124000, target: 100000 },
  ],
};

export const mockDashboardStats = {
  co2Saved: 4230,
  wasteReduced: 67,
  moneySaved: 2450000,
  activeProjects: 3,
};
