// Mock data for Bunyan - used when Supabase is not configured

export const mockUser = {
  id: "user-001",
  email: "mohamed@bunyan.ai",
  full_name: "Mohamed El-Sayed",
  company_name: "El-Sayed Construction",
  role: "contractor",
  avatar_url: null,
  phone: "+20 100 123 4567",
};

export const mockProjects = [
  {
    id: "proj-001",
    name: "Cairo Business District - Tower B",
    description: "Mixed-use commercial tower, 45 floors with sustainable design certification",
    location: "Cairo, Egypt",
    status: "active",
    budget: 12500000,
    spent: 8750000,
    waste_percentage: 4.2,
    sustainability_score: 87,
    co2_saved: 1240,
    start_date: "2025-03-15",
    end_date: "2026-09-30",
    created_at: "2025-03-10T08:00:00Z",
  },
  {
    id: "proj-002",
    name: "New Administrative Capital Residential Complex Phase 2",
    description: "Eco-friendly residential buildings with zero-waste target",
    location: "New Administrative Capital, Egypt",
    status: "active",
    budget: 8200000,
    spent: 3280000,
    waste_percentage: 2.8,
    sustainability_score: 94,
    co2_saved: 890,
    start_date: "2025-06-01",
    end_date: "2026-12-15",
    created_at: "2025-05-20T08:00:00Z",
  },
  {
    id: "proj-003",
    name: "Alexandria Waterfront Promenade",
    description: "Public walkway with sustainable infrastructure",
    location: "Alexandria, Egypt",
    status: "planning",
    budget: 3500000,
    spent: 175000,
    waste_percentage: 0,
    sustainability_score: 0,
    co2_saved: 0,
    start_date: "2026-01-15",
    end_date: "2026-08-30",
    created_at: "2025-11-05T08:00:00Z",
  },
  {
    id: "proj-004",
    name: "Cairo Metro Station - Green Line",
    description: "Underground transit station with energy-efficient systems",
    location: "Cairo, Egypt",
    status: "completed",
    budget: 5800000,
    spent: 5510000,
    waste_percentage: 3.1,
    sustainability_score: 91,
    co2_saved: 2100,
    start_date: "2024-06-01",
    end_date: "2025-11-30",
    created_at: "2024-05-15T08:00:00Z",
  },
];

export const mockMaterials = [
  {
    id: "mat-001",
    name: "EcoSteel Rebar Grade 60",
    category: "Steel",
    description: "High-strength recycled steel rebar with 85% recycled content",
    price: 3200,
    unit: "ton",
    supplier_name: "GreenSteel Arabia",
    eco_score: 92,
    co2_footprint: 1.2,
    recycled_content: 85,
    certification: "LEED Certified",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-002",
    name: "SustainCrete C40 Ready Mix",
    category: "Concrete",
    description: "Low-carbon concrete mix with 40% slag cement replacement",
    price: 450,
    unit: "m³",
    supplier_name: "Arabian Cement Co.",
    eco_score: 88,
    co2_footprint: 0.8,
    recycled_content: 40,
    certification: "ISO 14001",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-003",
    name: "BioInsulate Pro R-30",
    category: "Insulation",
    description: "Plant-based thermal insulation panels, zero VOC",
    price: 185,
    unit: "m²",
    supplier_name: "Desert Green Materials",
    eco_score: 96,
    co2_footprint: 0.3,
    recycled_content: 70,
    certification: "Cradle to Cradle",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-004",
    name: "SolarGlass Facade Panel",
    category: "Glass",
    description: "Triple-glazed photovoltaic glass panel for building facades",
    price: 890,
    unit: "m²",
    supplier_name: "Vision Glass KSA",
    eco_score: 91,
    co2_footprint: 0.6,
    recycled_content: 30,
    certification: "BREEAM Excellent",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-005",
    name: "RecycleBlock AAC B4",
    category: "Blocks",
    description: "Autoclaved aerated concrete blocks from recycled materials",
    price: 28,
    unit: "piece",
    supplier_name: "Egyptian Block Co.",
    eco_score: 85,
    co2_footprint: 0.4,
    recycled_content: 60,
    certification: "EGBC Certified",
    in_stock: true,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-006",
    name: "EcoTimber CLT Panel",
    category: "Wood",
    description: "Cross-laminated timber from certified sustainable forests",
    price: 620,
    unit: "m³",
    supplier_name: "Timber Gulf LLC",
    eco_score: 94,
    co2_footprint: -0.5,
    recycled_content: 0,
    certification: "FSC Certified",
    in_stock: false,
    verified: true,
    image_url: null,
  },
  {
    id: "mat-007",
    name: "GreenPipe PVC-Free",
    category: "Piping",
    description: "Bio-based plumbing pipes with zero PVC content",
    price: 42,
    unit: "meter",
    supplier_name: "AquaFlow Systems",
    eco_score: 89,
    co2_footprint: 0.2,
    recycled_content: 45,
    certification: "NSF Certified",
    in_stock: true,
    verified: false,
    image_url: null,
  },
  {
    id: "mat-008",
    name: "CoolRoof Reflective Membrane",
    category: "Roofing",
    description: "High-SRI reflective roofing membrane, reduces cooling costs by 30%",
    price: 95,
    unit: "m²",
    supplier_name: "SkyShield Roofing",
    eco_score: 87,
    co2_footprint: 0.5,
    recycled_content: 25,
    certification: "Energy Star",
    in_stock: true,
    verified: true,
    image_url: null,
  },
];

export const mockBills = [
  {
    id: "bill-001",
    project_id: "proj-001",
    title: "Steel Rebar Delivery - Batch 12",
    amount: 384000,
    category: "Materials",
    vendor: "GreenSteel Arabia",
    status: "paid",
    created_at: "2025-12-10T08:00:00Z",
  },
  {
    id: "bill-002",
    project_id: "proj-001",
    title: "Concrete Pour - Level 28-30",
    amount: 225000,
    category: "Materials",
    vendor: "Arabian Cement Co.",
    status: "approved",
    created_at: "2025-12-15T08:00:00Z",
  },
  {
    id: "bill-003",
    project_id: "proj-002",
    title: "Insulation Installation Phase 3",
    amount: 156000,
    category: "Labor & Materials",
    vendor: "Desert Green Materials",
    status: "pending",
    created_at: "2026-01-05T08:00:00Z",
  },
];

export const mockActivityLogs = [
  {
    id: "log-001",
    action: "project_updated",
    description: "Updated waste percentage for King Abdullah Tower B",
    created_at: "2026-02-15T08:30:00Z",
  },
  {
    id: "log-002",
    action: "bill_scanned",
    description: "Scanned and processed invoice from GreenSteel Arabia",
    created_at: "2026-02-14T16:45:00Z",
  },
  {
    id: "log-003",
    action: "ai_analysis",
    description: "AI generated cost optimization report for New Capital Phase 2",
    created_at: "2026-02-14T11:20:00Z",
  },
  {
    id: "log-004",
    action: "material_added",
    description: "Added SolarGlass Facade Panels to comparison list",
    created_at: "2026-02-13T09:15:00Z",
  },
  {
    id: "log-005",
    action: "project_created",
    description: "Created new project: Alexandria Waterfront Promenade",
    created_at: "2026-02-12T14:00:00Z",
  },
];

export const mockAnalyticsData = {
  wasteReduction: [
    { month: "Sep", value: 12.5 },
    { month: "Oct", value: 10.8 },
    { month: "Nov", value: 8.9 },
    { month: "Dec", value: 7.2 },
    { month: "Jan", value: 5.6 },
    { month: "Feb", value: 4.2 },
  ],
  co2Reduction: [
    { month: "Sep", value: 180 },
    { month: "Oct", value: 320 },
    { month: "Nov", value: 540 },
    { month: "Dec", value: 780 },
    { month: "Jan", value: 1050 },
    { month: "Feb", value: 1240 },
  ],
  budgetDistribution: [
    { name: "Materials", value: 45, color: "#102a4e" },
    { name: "Labor", value: 25, color: "#2e8c58" },
    { name: "Equipment", value: 15, color: "#788593" },
    { name: "Permits", value: 8, color: "#3aa86a" },
    { name: "Other", value: 7, color: "#9aa4ae" },
  ],
  monthlyOptimization: [
    { month: "Sep", saved: 45000, target: 60000 },
    { month: "Oct", saved: 62000, target: 60000 },
    { month: "Nov", saved: 78000, target: 75000 },
    { month: "Dec", saved: 91000, target: 80000 },
    { month: "Jan", saved: 105000, target: 90000 },
    { month: "Feb", saved: 124000, target: 100000 },
  ],
};

export const mockDashboardStats = {
  co2Saved: 4230,
  wasteReduced: 67,
  moneySaved: 2450000,
  activeProjects: 3,
};
